version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - teststack-network

  go-webapp:
    image: go-webapp:latest
    container_name: production_go-webapp
    environment:
      - SERVER_TEXT=${SERVER_TEXT}
    expose:
      - "8080"
    networks:
      - teststack-network

networks:
  teststack-network:
