version: "3"
services:
  nginx:
    image: local/nginx:latest
    container_name: "production_nginx"
    networks:
      - "teststack-network"
    ports:
      - "80:80"
  go-webapp:
    image: go-webapp:latest
    container_name: "production_go-webapp"
    environment:
      - SERVER_TEXT=${SERVER_TEXT}
    expose:
      - "8080"
    networks:
      - "teststack-network"
networks:
  "teststack-network":
