version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - setup_remote_docker
      - run: mkdir -p $TEST_RESULTS
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: go get gotest.tools/gotestsum
      - run: cd test && go mod download
      - run:
          name: Run unit tests
          command: |
            make test-unit
      - run: cp tmp/unit-report.xml /tmp/test-results/unit-report.xml
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results
